amazon.kms.cmk: arn:aws:kms:blablabla
chrome:
  headless.path: bin/headless-chromium
  driver:
    path: bin/chromedriver
    wait: 30
nestor.booker.pure:
  format:
    time: h:mm a
    date: dd/MM/yyyy
management.security.enabled: false