package org.gotson.nestor.infrastructure.persistence.dto

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import org.gotson.nestor.domain.model.Membership

@DynamoDBTable(tableName = "nestor_membership")
data class MembershipDynamo(
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String? = null,

        @DynamoDBAttribute
        var userId: String? = null,

        @DynamoDBAttribute
        var studioId: String? = null,

        @DynamoDBAttribute
        var login: String? = null,

        @DynamoDBAttribute
        var password: String? = null
) {
    companion object {
        fun from(membership: Membership): MembershipDynamo =
                MembershipDynamo(
                        membership.id,
                        membership.user.id,
                        membership.studio.id,
                        membership.login,
                        membership.password)
    }
}