package org.gotson.nestor.infrastructure.persistence.dto

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import org.gotson.nestor.domain.model.Studio

@DynamoDBTable(tableName = "nestor_studio")
data class StudioDynamo(
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String? = null,

        @DynamoDBAttribute
        var name: String? = null,

        @DynamoDBAttribute
        var url: String? = null
) {
    fun toDomain(): Studio =
            Studio(id, name!!, url!!)
}

fun Studio.toDtoDynamo(): StudioDynamo =
        StudioDynamo(id, name, url)