package org.gotson.nestor.infrastructure.persistence.dto

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import org.gotson.nestor.domain.model.User

@DynamoDBTable(tableName = "nestor_user")
data class UserDynamo(
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    var id: String? = null,

    @DynamoDBAttribute
    var email: String? = null,

    @DynamoDBAttribute
    var firstName: String? = null,

    @DynamoDBAttribute
    var lastName: String? = null,

    @DynamoDBAttribute
    var icalCalendars: List<String> = emptyList()
) {
  fun toDomain(): User =
      User(id, email!!, firstName!!, lastName!!, icalCalendars)
}

fun User.toDtoDynamo(): UserDynamo =
    UserDynamo(id, email, firstName, lastName, icalCalendars)