package org.gotson.nestor.infrastructure.persistence.dto

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import org.gotson.nestor.domain.model.User

@DynamoDBTable(tableName = "nestor_user")
data class UserDynamo(
        @DynamoDBHashKey
        @DynamoDBAutoGeneratedKey
        var id: String? = null,

        @DynamoDBAttribute
        var email: String? = null,

        @DynamoDBAttribute
        var firstName: String? = null,

        @DynamoDBAttribute
        var lastName: String? = null
) {
    companion object {
        fun from(user: User): UserDynamo =
                UserDynamo(user.id, user.email, user.firstName, user.lastName)
    }

    fun toDomain(): User =
            User(id, email!!, firstName!!, lastName!!)
}