application.version: ${version}

chrome.driver.wait: 30

nestor:
  schedule: 0 1 9 * * ?
  pure:
    advanceBookingDays: 2
    format:
      time: h:mm a
      date: dd/MM/yyyy

spring:
  h2:
    console:
      enabled: true

management.endpoints.web.exposure.include: "*"