application.version: ${version}

chrome.driver.wait: 30

nestor:
  schedule:
    booking: 0 1 9 * * ?
    deleteOld: 0 1 5 * * ?
  pure:
    advanceBookingDays: 2
    format:
      time: h:mm a
      date: d/MM/yyyy

spring:
  h2:
    console:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    #    username: username
    #    password: password
    properties:
      mail.smtp:
        auth: true
        starttls.enable: true

management.endpoints.web.exposure.include: "*"